function x_hat_d = coopObserver(in1)
%coopObserver
%    X_HAT_D = coopObserver(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    29-Jun-2024 14:19:28

ct1 = in1(4,:);
ct2 = in1(5,:);
ui = in1(3,:);
x_hat2 = in1(2,:);
x_hat_d = [-ct1+x_hat2;-ct2-ui.*9.9453-x_hat2];
end
