function xhd = coopObserver(in1)
%coopObserver
%    XHD = coopObserver(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    14-Jun-2024 13:33:15

ct1 = in1(4,:);
ct2 = in1(5,:);
ui = in1(3,:);
x_hat2 = in1(2,:);
xhd = [-ct1+x_hat2;-ct2-ui.*9.9453-x_hat2./2.0];
end
