function x_hat_d = gen_coopObserver(in1)
%gen_coopObserver
%    X_HAT_D = gen_coopObserver(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    29-Jun-2024 18:57:07

ct1 = in1(4,:);
ct2 = in1(5,:);
ui = in1(3,:);
x_hat2 = in1(2,:);
x_hat_d = [-ct1+x_hat2;-ct2-ui.*9.9453-x_hat2./2.0];
end
